# Generated by Django 5.2 on 2025-07-23 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFeatures',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a7335455-7e56-46a0-887a-e317f078ebec'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='Features_icon/')),
                ('available_number', models.CharField(max_length=20)),
                ('show_icon_only', models.BooleanField(default=False)),
                ('show_name_only', models.BooleanField(default=False)),
                ('add_available_number', models.BooleanField(default=False)),
                ('is_additional_image_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HouseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a3a3a903-3809-4837-b78d-1be5a640e9ec'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'House Categories',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to='Houses/')),
                ('payment_category', models.CharField(choices=[('Rent', 'For Rent'), ('Sell', 'For Sell')], max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('house_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseManagement.housecategory')),
            ],
        ),
        migrations.CreateModel(
            name='HouseFeatureAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_assignments', to='HouseManagement.additionalfeatures')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_assignments', to='HouseManagement.house')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='house_features',
            field=models.ManyToManyField(related_name='houses', through='HouseManagement.HouseFeatureAssignment', to='HouseManagement.additionalfeatures'),
        ),
        migrations.CreateModel(
            name='HouseFeatureImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='HouseFeaturePhotos/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='HouseManagement.housefeatureassignment')),
            ],
        ),
    ]
