# Generated by Django 5.2 on 2025-08-07 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFeatures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='Features_icon/')),
                ('show_available_number', models.BooleanField(default=False)),
                ('show_icon_only', models.BooleanField(default=False)),
                ('show_name_only', models.BooleanField(default=False)),
                ('add_available_number', models.BooleanField(default=False)),
                ('is_additional_image_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HouseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'House Categories',
            },
        ),
        migrations.CreateModel(
            name='Proximity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=23, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=23, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('thumbnail', models.ImageField(upload_to='Houses/')),
                ('payment_category', models.CharField(choices=[('Rent', 'For Rent'), ('Sell', 'For Sell')], max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=23, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=23, null=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('is_booked', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_houses', to=settings.AUTH_USER_MODEL)),
                ('house_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseManagement.housecategory')),
            ],
        ),
        migrations.CreateModel(
            name='HouseFeatureAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('available_number', models.CharField(blank=True, max_length=20, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_assignments', to='HouseManagement.additionalfeatures')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_assignments', to='HouseManagement.house')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='house_features',
            field=models.ManyToManyField(related_name='houses', through='HouseManagement.HouseFeatureAssignment', to='HouseManagement.additionalfeatures'),
        ),
        migrations.CreateModel(
            name='HouseFeatureImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='HouseFeaturePhotos/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='HouseManagement.housefeatureassignment')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('images', models.ImageField(upload_to='Houses/House Images/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_images', to='HouseManagement.house')),
            ],
        ),
    ]
