# Generated by Django 5.2 on 2025-08-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proximity',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='approximity_icon/'),
        ),
    ]
