# Generated by Django 5.2 on 2025-07-23 11:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfeatures',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9bbeda9f-3e14-445b-88ab-7d62bfbee711'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='housecategory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ae222679-ef4f-424b-9706-9088ecc1577e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='housefeatureassignment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='housefeatureimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
