# Generated by Django 5.2 on 2025-07-23 11:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManagement', '0002_alter_additionalfeatures_id_alter_house_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfeatures',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='housecategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
