# Generated by Django 5.2 on 2025-08-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManagement', '0003_agent_alter_house_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.CharField(default='owner', max_length=20),
        ),
    ]
