# Generated by Django 5.2 on 2025-07-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManagement', '0003_alter_additionalfeatures_id_alter_housecategory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalfeatures',
            name='available_number',
        ),
        migrations.AddField(
            model_name='additionalfeatures',
            name='show_available_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housefeatureassignment',
            name='available_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
