# Generated by Django 5.2 on 2025-07-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManagement', '0004_remove_additionalfeatures_available_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='house',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
