# Generated by Django 5.2 on 2025-07-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManagement', '0005_rename_location_house_address_house_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
