# Generated by Django 5.2 on 2025-07-28 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManagement', '0006_house_is_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proximity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('images', models.ImageField(upload_to='Houses/House Images/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_images', to='HouseManagement.house')),
            ],
        ),
    ]
