# Generated by Django 5.2 on 2025-07-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManagement', '0011_alter_house_latitude_alter_house_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='proximity',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='proximity',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=23, null=True),
        ),
    ]
